# Generated by Django 3.0.7 on 2020-06-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pub_date',
        ),
    ]
