# Generated by Django 3.0.7 on 2020-06-16 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pease', '0004_auto_20200616_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='New York', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(default='sk', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(default='object-oriented', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
